{
  "build": {
    "builder": "NIXPACKS"
  },
  "deploy": {
    "startCommand": "uvicorn co.edu.uco.retnova.interfaces.api.main:app --host 0.0.0.0 --port $PORT",
    "workdir": "IS2-RetNova-Desarrollo"
  }
}
